// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/Scribe.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// clr
NumericMatrix clr(NumericMatrix x);
RcppExport SEXP _Scribe_clr(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(clr(x));
    return rcpp_result_gen;
END_RCPP
}
// kde_cpp
NumericMatrix kde_cpp(NumericMatrix data, int k, int b, int pdf, int density_sample_type);
static SEXP _Scribe_kde_cpp_try(SEXP dataSEXP, SEXP kSEXP, SEXP bSEXP, SEXP pdfSEXP, SEXP density_sample_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type pdf(pdfSEXP);
    Rcpp::traits::input_parameter< int >::type density_sample_type(density_sample_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_cpp(data, k, b, pdf, density_sample_type));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_kde_cpp(SEXP dataSEXP, SEXP kSEXP, SEXP bSEXP, SEXP pdfSEXP, SEXP density_sample_typeSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_kde_cpp_try(dataSEXP, kSEXP, bSEXP, pdfSEXP, density_sample_typeSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// kde
NumericMatrix kde(SEXP data, SEXP k, SEXP b, SEXP pdf, SEXP density_sample_type);
static SEXP _Scribe_kde_try(SEXP dataSEXP, SEXP kSEXP, SEXP bSEXP, SEXP pdfSEXP, SEXP density_sample_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pdf(pdfSEXP);
    Rcpp::traits::input_parameter< SEXP >::type density_sample_type(density_sample_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(kde(data, k, b, pdf, density_sample_type));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_kde(SEXP dataSEXP, SEXP kSEXP, SEXP bSEXP, SEXP pdfSEXP, SEXP density_sample_typeSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_kde_try(dataSEXP, kSEXP, bSEXP, pdfSEXP, density_sample_typeSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// knn_density
List knn_density(SEXP x, SEXP y, SEXP k);
static SEXP _Scribe_knn_density_try(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_density(x, y, k));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_knn_density(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_knn_density_try(xSEXP, ySEXP, kSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// knn_density_2d
NumericMatrix knn_density_2d(SEXP x, SEXP y, SEXP nGrids, SEXP k);
static SEXP _Scribe_knn_density_2d_try(SEXP xSEXP, SEXP ySEXP, SEXP nGridsSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type nGrids(nGridsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_density_2d(x, y, nGrids, k));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_knn_density_2d(SEXP xSEXP, SEXP ySEXP, SEXP nGridsSEXP, SEXP kSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_knn_density_2d_try(xSEXP, ySEXP, nGridsSEXP, kSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// digamma_0
double digamma_0(double x);
static SEXP _Scribe_digamma_0_try(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(digamma_0(x));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_digamma_0(SEXP xSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_digamma_0_try(xSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// vd
double vd(SEXP d);
static SEXP _Scribe_vd_try(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(vd(d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_vd(SEXP dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_vd_try(dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// entropy
double entropy(SEXP x, SEXP k);
static SEXP _Scribe_entropy_try(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(entropy(x, k));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_entropy(SEXP xSEXP, SEXP kSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_entropy_try(xSEXP, kSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// mi
double mi(SEXP x, SEXP y, SEXP k, SEXP normalize);
static SEXP _Scribe_mi_try(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(mi(x, y, k, normalize));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_mi(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP normalizeSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_mi_try(xSEXP, ySEXP, kSEXP, normalizeSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cmi
List cmi(SEXP x, SEXP y, SEXP z, SEXP k, SEXP normalize);
static SEXP _Scribe_cmi_try(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP kSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cmi(x, y, z, k, normalize));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_cmi(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP kSEXP, SEXP normalizeSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_cmi_try(xSEXP, ySEXP, zSEXP, kSEXP, normalizeSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// ucmi_cpp
List ucmi_cpp(const NumericMatrix& x, const NumericMatrix& y, NumericMatrix z, int k, int method, int k_density, double bw);
static SEXP _Scribe_ucmi_cpp_try(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type k_density(k_densitySEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(ucmi_cpp(x, y, z, k, method, k_density, bw));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_ucmi_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_ucmi_cpp_try(xSEXP, ySEXP, zSEXP, kSEXP, methodSEXP, k_densitySEXP, bwSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// ucmi
List ucmi(SEXP x, SEXP y, SEXP z, SEXP k, SEXP method, SEXP k_density, SEXP bw);
static SEXP _Scribe_ucmi_try(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type method(methodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k_density(k_densitySEXP);
    Rcpp::traits::input_parameter< SEXP >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(ucmi(x, y, z, k, method, k_density, bw));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_ucmi(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_ucmi_try(xSEXP, ySEXP, zSEXP, kSEXP, methodSEXP, k_densitySEXP, bwSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// umi_cpp
double umi_cpp(const NumericMatrix& x, const NumericMatrix& y, int k, int method, int k_density, double bw);
static SEXP _Scribe_umi_cpp_try(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type k_density(k_densitySEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(umi_cpp(x, y, k, method, k_density, bw));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_umi_cpp(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_umi_cpp_try(xSEXP, ySEXP, kSEXP, methodSEXP, k_densitySEXP, bwSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// umi
double umi(SEXP x, SEXP y, SEXP k, SEXP method, SEXP k_density, SEXP bw);
static SEXP _Scribe_umi_try(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type method(methodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k_density(k_densitySEXP);
    Rcpp::traits::input_parameter< SEXP >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(umi(x, y, k, method, k_density, bw));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _Scribe_umi(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_Scribe_umi_try(xSEXP, ySEXP, kSEXP, methodSEXP, k_densitySEXP, bwSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// di_single_run
double di_single_run(SEXP x, SEXP y, SEXP n, SEXP uniformalize);
RcppExport SEXP _Scribe_di_single_run(SEXP xSEXP, SEXP ySEXP, SEXP nSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type n(nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(di_single_run(x, y, n, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// di_single_run_conditioned
double di_single_run_conditioned(SEXP x, SEXP y, SEXP z, SEXP n, SEXP uniformalize);
RcppExport SEXP _Scribe_di_single_run_conditioned(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP nSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n(nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(di_single_run_conditioned(x, y, z, n, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// rdi_many_runs
double rdi_many_runs(SEXP x, SEXP y, SEXP uniformalize);
RcppExport SEXP _Scribe_rdi_many_runs(SEXP xSEXP, SEXP ySEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rdi_many_runs(x, y, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// rdi_single_run
double rdi_single_run(SEXP x, SEXP y, SEXP d, SEXP uniformalize);
RcppExport SEXP _Scribe_rdi_single_run(SEXP xSEXP, SEXP ySEXP, SEXP dSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type d(dSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rdi_single_run(x, y, d, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// lmi_single_run
double lmi_single_run(SEXP x, SEXP y, SEXP delay, SEXP umi);
RcppExport SEXP _Scribe_lmi_single_run(SEXP xSEXP, SEXP ySEXP, SEXP delaySEXP, SEXP umiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type delay(delaySEXP);
    Rcpp::traits::input_parameter< SEXP >::type umi(umiSEXP);
    rcpp_result_gen = Rcpp::wrap(lmi_single_run(x, y, delay, umi));
    return rcpp_result_gen;
END_RCPP
}
// lmi_multiple_run_cpp
double lmi_multiple_run_cpp(NumericMatrix& x, NumericMatrix& y, int d, IntegerVector run_vec, bool uniformalize);
RcppExport SEXP _Scribe_lmi_multiple_run_cpp(SEXP xSEXP, SEXP ySEXP, SEXP dSEXP, SEXP run_vecSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(lmi_multiple_run_cpp(x, y, d, run_vec, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// lmi_multiple_run
double lmi_multiple_run(SEXP x, SEXP y, SEXP d, SEXP run_vec, SEXP umi);
RcppExport SEXP _Scribe_lmi_multiple_run(SEXP xSEXP, SEXP ySEXP, SEXP dSEXP, SEXP run_vecSEXP, SEXP umiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type d(dSEXP);
    Rcpp::traits::input_parameter< SEXP >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< SEXP >::type umi(umiSEXP);
    rcpp_result_gen = Rcpp::wrap(lmi_multiple_run(x, y, d, run_vec, umi));
    return rcpp_result_gen;
END_RCPP
}
// rdi_single_run_conditioned
double rdi_single_run_conditioned(SEXP x, SEXP y, SEXP z, SEXP z_delays, SEXP d, SEXP uniformalize);
RcppExport SEXP _Scribe_rdi_single_run_conditioned(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP z_delaysSEXP, SEXP dSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type z_delays(z_delaysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type d(dSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rdi_single_run_conditioned(x, y, z, z_delays, d, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// extract_max_rdi_value_delay
List extract_max_rdi_value_delay(NumericMatrix rdi_result, IntegerVector delays);
RcppExport SEXP _Scribe_extract_max_rdi_value_delay(SEXP rdi_resultSEXP, SEXP delaysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rdi_result(rdi_resultSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delays(delaysSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_max_rdi_value_delay(rdi_result, delays));
    return rcpp_result_gen;
END_RCPP
}
// calculate_rdi_cpp
List calculate_rdi_cpp(NumericMatrix& expr_data, IntegerVector delays, IntegerMatrix& super_graph, IntegerVector& turning_points, int method, bool uniformalize);
RcppExport SEXP _Scribe_calculate_rdi_cpp(SEXP expr_dataSEXP, SEXP delaysSEXP, SEXP super_graphSEXP, SEXP turning_pointsSEXP, SEXP methodSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delays(delaysSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type turning_points(turning_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_rdi_cpp(expr_data, delays, super_graph, turning_points, method, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// calculate_rdi_cpp_wrap
List calculate_rdi_cpp_wrap(SEXP expr_data, SEXP delays, SEXP super_graph, SEXP turning_points, SEXP method, SEXP uniformalize);
RcppExport SEXP _Scribe_calculate_rdi_cpp_wrap(SEXP expr_dataSEXP, SEXP delaysSEXP, SEXP super_graphSEXP, SEXP turning_pointsSEXP, SEXP methodSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type delays(delaysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< SEXP >::type turning_points(turning_pointsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type method(methodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_rdi_cpp_wrap(expr_data, delays, super_graph, turning_points, method, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// extract_top_incoming_nodes_delays
List extract_top_incoming_nodes_delays(NumericMatrix max_rdi_value, IntegerMatrix max_rdi_delays, int k);
RcppExport SEXP _Scribe_extract_top_incoming_nodes_delays(SEXP max_rdi_valueSEXP, SEXP max_rdi_delaysSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type max_rdi_value(max_rdi_valueSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type max_rdi_delays(max_rdi_delaysSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_top_incoming_nodes_delays(max_rdi_value, max_rdi_delays, k));
    return rcpp_result_gen;
END_RCPP
}
// calculate_conditioned_rdi_cpp_wrap
NumericMatrix calculate_conditioned_rdi_cpp_wrap(SEXP expr_data, SEXP super_graph, SEXP max_rdi_value, SEXP max_rdi_delays, SEXP k, SEXP uniformalize);
RcppExport SEXP _Scribe_calculate_conditioned_rdi_cpp_wrap(SEXP expr_dataSEXP, SEXP super_graphSEXP, SEXP max_rdi_valueSEXP, SEXP max_rdi_delaysSEXP, SEXP kSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_rdi_value(max_rdi_valueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_rdi_delays(max_rdi_delaysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_conditioned_rdi_cpp_wrap(expr_data, super_graph, max_rdi_value, max_rdi_delays, k, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// smooth_gene
NumericMatrix smooth_gene(NumericMatrix& expr_data, const int window_size);
RcppExport SEXP _Scribe_smooth_gene(SEXP expr_dataSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< const int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(smooth_gene(expr_data, window_size));
    return rcpp_result_gen;
END_RCPP
}
// rdi_multiple_run_cpp
double rdi_multiple_run_cpp(NumericMatrix& x, NumericMatrix& y, int d, IntegerVector run_vec, bool uniformalize);
RcppExport SEXP _Scribe_rdi_multiple_run_cpp(SEXP xSEXP, SEXP ySEXP, SEXP dSEXP, SEXP run_vecSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rdi_multiple_run_cpp(x, y, d, run_vec, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// calculate_rdi_multiple_run_cpp
List calculate_rdi_multiple_run_cpp(NumericMatrix& expr_data, IntegerVector delays, IntegerVector run_vec, IntegerMatrix& super_graph, IntegerVector turning_points, int method, bool uniformalize);
RcppExport SEXP _Scribe_calculate_rdi_multiple_run_cpp(SEXP expr_dataSEXP, SEXP delaysSEXP, SEXP run_vecSEXP, SEXP super_graphSEXP, SEXP turning_pointsSEXP, SEXP methodSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type delays(delaysSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type turning_points(turning_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_rdi_multiple_run_cpp(expr_data, delays, run_vec, super_graph, turning_points, method, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// calculate_rdi_multiple_run_cpp_wrap
List calculate_rdi_multiple_run_cpp_wrap(SEXP expr_data, SEXP delays, SEXP run_vec, SEXP super_graph, SEXP turning_points, SEXP method, SEXP uniformalize);
RcppExport SEXP _Scribe_calculate_rdi_multiple_run_cpp_wrap(SEXP expr_dataSEXP, SEXP delaysSEXP, SEXP run_vecSEXP, SEXP super_graphSEXP, SEXP turning_pointsSEXP, SEXP methodSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type delays(delaysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< SEXP >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< SEXP >::type turning_points(turning_pointsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type method(methodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_rdi_multiple_run_cpp_wrap(expr_data, delays, run_vec, super_graph, turning_points, method, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// rdi_multiple_runs_conditioned_cpp
double rdi_multiple_runs_conditioned_cpp(NumericMatrix& x, NumericMatrix& y, NumericMatrix& z, IntegerVector& z_delays, int d, IntegerVector run_vec, bool uniformalize);
RcppExport SEXP _Scribe_rdi_multiple_runs_conditioned_cpp(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP z_delaysSEXP, SEXP dSEXP, SEXP run_vecSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type z_delays(z_delaysSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rdi_multiple_runs_conditioned_cpp(x, y, z, z_delays, d, run_vec, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// rdi_multiple_runs_conditioned
double rdi_multiple_runs_conditioned(SEXP x, SEXP y, SEXP z, SEXP z_delays, SEXP d, SEXP run_vec, SEXP uniformalize);
RcppExport SEXP _Scribe_rdi_multiple_runs_conditioned(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP z_delaysSEXP, SEXP dSEXP, SEXP run_vecSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    Rcpp::traits::input_parameter< SEXP >::type z_delays(z_delaysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type d(dSEXP);
    Rcpp::traits::input_parameter< SEXP >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rdi_multiple_runs_conditioned(x, y, z, z_delays, d, run_vec, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// calculate_conditioned_rdi_multiple_run_cpp
NumericMatrix calculate_conditioned_rdi_multiple_run_cpp(NumericMatrix& expr_data, IntegerMatrix& super_graph, NumericMatrix& max_rdi_value, IntegerMatrix& max_rdi_delays, IntegerVector run_vec, int k, bool uniformalize);
RcppExport SEXP _Scribe_calculate_conditioned_rdi_multiple_run_cpp(SEXP expr_dataSEXP, SEXP super_graphSEXP, SEXP max_rdi_valueSEXP, SEXP max_rdi_delaysSEXP, SEXP run_vecSEXP, SEXP kSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type max_rdi_value(max_rdi_valueSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type max_rdi_delays(max_rdi_delaysSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_conditioned_rdi_multiple_run_cpp(expr_data, super_graph, max_rdi_value, max_rdi_delays, run_vec, k, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// calculate_conditioned_rdi_multiple_run_wrap
NumericMatrix calculate_conditioned_rdi_multiple_run_wrap(SEXP expr_data, SEXP super_graph, SEXP max_rdi_value, SEXP max_rdi_delays, SEXP run_vec, SEXP k, SEXP uniformalize);
RcppExport SEXP _Scribe_calculate_conditioned_rdi_multiple_run_wrap(SEXP expr_dataSEXP, SEXP super_graphSEXP, SEXP max_rdi_valueSEXP, SEXP max_rdi_delaysSEXP, SEXP run_vecSEXP, SEXP kSEXP, SEXP uniformalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_rdi_value(max_rdi_valueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max_rdi_delays(max_rdi_delaysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type run_vec(run_vecSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type uniformalize(uniformalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_conditioned_rdi_multiple_run_wrap(expr_data, super_graph, max_rdi_value, max_rdi_delays, run_vec, k, uniformalize));
    return rcpp_result_gen;
END_RCPP
}
// calculate_umi_cpp
NumericMatrix calculate_umi_cpp(NumericMatrix& expr_data, IntegerMatrix& super_graph, int k, int method, int k_density, double bw);
RcppExport SEXP _Scribe_calculate_umi_cpp(SEXP expr_dataSEXP, SEXP super_graphSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix& >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type k_density(k_densitySEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_umi_cpp(expr_data, super_graph, k, method, k_density, bw));
    return rcpp_result_gen;
END_RCPP
}
// calculate_umi_cpp_wrap
NumericMatrix calculate_umi_cpp_wrap(SEXP expr_data, SEXP super_graph, SEXP k, SEXP method, SEXP k_density, SEXP bw);
RcppExport SEXP _Scribe_calculate_umi_cpp_wrap(SEXP expr_dataSEXP, SEXP super_graphSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP k_densitySEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type super_graph(super_graphSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k(kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type method(methodSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k_density(k_densitySEXP);
    Rcpp::traits::input_parameter< SEXP >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_umi_cpp_wrap(expr_data, super_graph, k, method, k_density, bw));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _Scribe_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericMatrix(*kde_cpp)(NumericMatrix,int,int,int,int)");
        signatures.insert("NumericMatrix(*kde)(SEXP,SEXP,SEXP,SEXP,SEXP)");
        signatures.insert("List(*knn_density)(SEXP,SEXP,SEXP)");
        signatures.insert("NumericMatrix(*knn_density_2d)(SEXP,SEXP,SEXP,SEXP)");
        signatures.insert("double(*digamma_0)(double)");
        signatures.insert("double(*vd)(SEXP)");
        signatures.insert("double(*entropy)(SEXP,SEXP)");
        signatures.insert("double(*mi)(SEXP,SEXP,SEXP,SEXP)");
        signatures.insert("List(*cmi)(SEXP,SEXP,SEXP,SEXP,SEXP)");
        signatures.insert("List(*ucmi_cpp)(const NumericMatrix&,const NumericMatrix&,NumericMatrix,int,int,int,double)");
        signatures.insert("List(*ucmi)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP)");
        signatures.insert("double(*umi_cpp)(const NumericMatrix&,const NumericMatrix&,int,int,int,double)");
        signatures.insert("double(*umi)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _Scribe_RcppExport_registerCCallable() { 
    R_RegisterCCallable("Scribe", "_Scribe_kde_cpp", (DL_FUNC)_Scribe_kde_cpp_try);
    R_RegisterCCallable("Scribe", "_Scribe_kde", (DL_FUNC)_Scribe_kde_try);
    R_RegisterCCallable("Scribe", "_Scribe_knn_density", (DL_FUNC)_Scribe_knn_density_try);
    R_RegisterCCallable("Scribe", "_Scribe_knn_density_2d", (DL_FUNC)_Scribe_knn_density_2d_try);
    R_RegisterCCallable("Scribe", "_Scribe_digamma_0", (DL_FUNC)_Scribe_digamma_0_try);
    R_RegisterCCallable("Scribe", "_Scribe_vd", (DL_FUNC)_Scribe_vd_try);
    R_RegisterCCallable("Scribe", "_Scribe_entropy", (DL_FUNC)_Scribe_entropy_try);
    R_RegisterCCallable("Scribe", "_Scribe_mi", (DL_FUNC)_Scribe_mi_try);
    R_RegisterCCallable("Scribe", "_Scribe_cmi", (DL_FUNC)_Scribe_cmi_try);
    R_RegisterCCallable("Scribe", "_Scribe_ucmi_cpp", (DL_FUNC)_Scribe_ucmi_cpp_try);
    R_RegisterCCallable("Scribe", "_Scribe_ucmi", (DL_FUNC)_Scribe_ucmi_try);
    R_RegisterCCallable("Scribe", "_Scribe_umi_cpp", (DL_FUNC)_Scribe_umi_cpp_try);
    R_RegisterCCallable("Scribe", "_Scribe_umi", (DL_FUNC)_Scribe_umi_try);
    R_RegisterCCallable("Scribe", "_Scribe_RcppExport_validate", (DL_FUNC)_Scribe_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_Scribe_clr", (DL_FUNC) &_Scribe_clr, 1},
    {"_Scribe_kde_cpp", (DL_FUNC) &_Scribe_kde_cpp, 5},
    {"_Scribe_kde", (DL_FUNC) &_Scribe_kde, 5},
    {"_Scribe_knn_density", (DL_FUNC) &_Scribe_knn_density, 3},
    {"_Scribe_knn_density_2d", (DL_FUNC) &_Scribe_knn_density_2d, 4},
    {"_Scribe_digamma_0", (DL_FUNC) &_Scribe_digamma_0, 1},
    {"_Scribe_vd", (DL_FUNC) &_Scribe_vd, 1},
    {"_Scribe_entropy", (DL_FUNC) &_Scribe_entropy, 2},
    {"_Scribe_mi", (DL_FUNC) &_Scribe_mi, 4},
    {"_Scribe_cmi", (DL_FUNC) &_Scribe_cmi, 5},
    {"_Scribe_ucmi_cpp", (DL_FUNC) &_Scribe_ucmi_cpp, 7},
    {"_Scribe_ucmi", (DL_FUNC) &_Scribe_ucmi, 7},
    {"_Scribe_umi_cpp", (DL_FUNC) &_Scribe_umi_cpp, 6},
    {"_Scribe_umi", (DL_FUNC) &_Scribe_umi, 6},
    {"_Scribe_di_single_run", (DL_FUNC) &_Scribe_di_single_run, 4},
    {"_Scribe_di_single_run_conditioned", (DL_FUNC) &_Scribe_di_single_run_conditioned, 5},
    {"_Scribe_rdi_many_runs", (DL_FUNC) &_Scribe_rdi_many_runs, 3},
    {"_Scribe_rdi_single_run", (DL_FUNC) &_Scribe_rdi_single_run, 4},
    {"_Scribe_lmi_single_run", (DL_FUNC) &_Scribe_lmi_single_run, 4},
    {"_Scribe_lmi_multiple_run_cpp", (DL_FUNC) &_Scribe_lmi_multiple_run_cpp, 5},
    {"_Scribe_lmi_multiple_run", (DL_FUNC) &_Scribe_lmi_multiple_run, 5},
    {"_Scribe_rdi_single_run_conditioned", (DL_FUNC) &_Scribe_rdi_single_run_conditioned, 6},
    {"_Scribe_extract_max_rdi_value_delay", (DL_FUNC) &_Scribe_extract_max_rdi_value_delay, 2},
    {"_Scribe_calculate_rdi_cpp", (DL_FUNC) &_Scribe_calculate_rdi_cpp, 6},
    {"_Scribe_calculate_rdi_cpp_wrap", (DL_FUNC) &_Scribe_calculate_rdi_cpp_wrap, 6},
    {"_Scribe_extract_top_incoming_nodes_delays", (DL_FUNC) &_Scribe_extract_top_incoming_nodes_delays, 3},
    {"_Scribe_calculate_conditioned_rdi_cpp_wrap", (DL_FUNC) &_Scribe_calculate_conditioned_rdi_cpp_wrap, 6},
    {"_Scribe_smooth_gene", (DL_FUNC) &_Scribe_smooth_gene, 2},
    {"_Scribe_rdi_multiple_run_cpp", (DL_FUNC) &_Scribe_rdi_multiple_run_cpp, 5},
    {"_Scribe_calculate_rdi_multiple_run_cpp", (DL_FUNC) &_Scribe_calculate_rdi_multiple_run_cpp, 7},
    {"_Scribe_calculate_rdi_multiple_run_cpp_wrap", (DL_FUNC) &_Scribe_calculate_rdi_multiple_run_cpp_wrap, 7},
    {"_Scribe_rdi_multiple_runs_conditioned_cpp", (DL_FUNC) &_Scribe_rdi_multiple_runs_conditioned_cpp, 7},
    {"_Scribe_rdi_multiple_runs_conditioned", (DL_FUNC) &_Scribe_rdi_multiple_runs_conditioned, 7},
    {"_Scribe_calculate_conditioned_rdi_multiple_run_cpp", (DL_FUNC) &_Scribe_calculate_conditioned_rdi_multiple_run_cpp, 7},
    {"_Scribe_calculate_conditioned_rdi_multiple_run_wrap", (DL_FUNC) &_Scribe_calculate_conditioned_rdi_multiple_run_wrap, 7},
    {"_Scribe_calculate_umi_cpp", (DL_FUNC) &_Scribe_calculate_umi_cpp, 6},
    {"_Scribe_calculate_umi_cpp_wrap", (DL_FUNC) &_Scribe_calculate_umi_cpp_wrap, 6},
    {"_Scribe_RcppExport_registerCCallable", (DL_FUNC) &_Scribe_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Scribe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
